### ISSUE TITLE
Lab B1 - AuthenticationError: 401 status code (no body)

### ISSUE THREAD

**Issue by mohammadamer** [microsoft/copilot-camp#309]
Here is the terminal log.

Debugger attached.
CHAT PROMPT:
[
  {
    "role": "system",
    "content": "You are a career specialist named \"Career Genie\" that helps Human Resources team for writing job posts.\r\nYou are friendly and professional.\r\nYou always greet users with excitement and introduce yourself first.\r\nYou like using emojis where appropriate."        
  },
  {
    "role": "user",
    "content": "hi"
  }
]
AuthenticationError: 401 status code (no body)
    at Function.generate (C:\CareerGenie\node_modules\openai\src\error.ts:74:14)
    at AzureOpenAI.makeStatusError (C:\CareerGenie\node_modules\openai\src\core.ts:428:21)
    at AzureOpenAI.makeRequest (C:\CareerGenie\node_modules\openai\src\core.ts:492:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async OpenAIModel.completePrompt (C:\CareerGenie\node_modules\@microsoft\teams-ai\src\models\OpenAIModel.ts:359:32)
    at async LLMClient.callCompletePrompt (C:\CareerGenie\node_modules\@microsoft\teams-ai\src\planners\LLMClient.ts:376:31)
    at async LLMClient.completePrompt (C:\CareerGenie\node_modules\@microsoft\teams-ai\src\planners\LLMClient.ts:333:30)
    at async ActionPlanner.completePrompt (C:\CareerGenie\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:272:16)
    at async ActionPlanner.continueTask (C:\CareerGenie\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:191:24)
    at async ActionPlanner.beginTask (C:\CareerGenie\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:166:16) {
  status: 401,
  headers: {
    'content-length': '152',
    'content-type': 'application/json',
    date: 'Sat, 28 Sep 2024 18:01:55 GMT',
    'request-context': 'appId=cid-v1:4893ede5-bbb3-486d-a706-6c506afa8d4b',
    'www-authenticate': 'AzureApiManagementKey realm="https://zyx/openai",name="Ocp-Apim-Subscription-Key",type="header"'     
  },
  request_id: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
ERROR:
401 status code (no body)
HEADERS:
{
  "content-length": "152",
  "content-type": "application/json",
  "date": "Sat, 28 Sep 2024 18:01:55 GMT",
  "request-context": "appId=cid-v1:4893ede5-bbb3-486d-a706-6c506afa8d4b",
  "www-authenticate": "AzureApiManagementKey realm=\"https://xyz/openai\",name=\"Ocp-Apim-Subscription-Key\",type=\"header\"" 
}

 [onTurnError] unhandled error: Error: The chat completion API returned an error status of 401: Error

**Comment by rabwill** [comment]
@mohammadamer Could you let us know more info like what is the Azure OpenAI service info you are using like:
Model
Deployment version etc

**Comment by mohammadamer** [comment]
@rabwill 
Model: gpt-35-turbo
deployment version: 2023-03-15-preview

**Comment by rabwill** [comment]
Thank you so much Mohammad, I will get back to you soon.

**Comment by mohammadamer** [comment]
Thank you @rabwill for making the effort to replicate the issue. I have debug in test tool option.
I encountered some challenges as well, but fortunately, after setting up a new Azure Open AI instance under a different Subscription, the problem was resolved.

**Comment by rabwill** [comment]
Great to hear @mohammadamer closing this now :)
